name: restaurants_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: 
  retrofit: ^4.0.1
  analyzer: 
  dio: ^5.2.1+1
  json_serializable: 
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: 
  freezed: ^2.3.5
  get_it: ^7.6.0
  lottie:
  country_code_picker: ^3.0.0
  image_picker: 
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  easy_localization: 
  flutter_phoenix: 
  easy_search_bar: ^2.5.0
  # flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.5
  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.1+1
  build_runner:  
  internet_connection_checker: ^1.0.0+1

  
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/mac.jpg
    - assets/images/kfc.jpg
    - assets/images/burger_king.jpg
    - assets/images/subway.jpg
    - assets/images/pizza_hut.jpg
    - assets/images/res6.jpg
    - assets/images/res7.jpg
    - assets/images/res8.jpg
    - assets/images/res9.jpg
    - assets/images/res10.jpg
    - assets/images/onboardingLogo1.png
    - assets/images/onboardingLogo2.png
    - assets/images/onboardingLogo3.png
    - assets/images/right_arrow_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/change_lang_ic.svg
    - assets/images/contact_us_ic.svg
    - assets/images/invite_friends_ic.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/settings_right_arrow_ic.svg
    - assets/images/logout_ic.svg
    - assets/images/photo_camera.svg
  
 

    - assets/json/empty.json
    - assets/json/error.json
    - assets/json/loading.json
    - assets/json/success.json
    - assets/json/coming_soon.json
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf  
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf  
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf  
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf  
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
