// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1uA88jhxXQzKeR-TlIvpj0gknlJBRhQY',
    appId: '1:481748479821:web:57a17469abe357d7fc5104',
    messagingSenderId: '481748479821',
    projectId: 'restaurants-notifications',
    authDomain: 'restaurants-notifications.firebaseapp.com',
    storageBucket: 'restaurants-notifications.appspot.com',
    measurementId: 'G-HZM7CCDCVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZPXSAlF7HfQ8rcps9fcvGS9xI2FsPB4',
    appId: '1:481748479821:android:262856849846f52bfc5104',
    messagingSenderId: '481748479821',
    projectId: 'restaurants-notifications',
    storageBucket: 'restaurants-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1qE9XGgNl8YkVyT3bnv-OB97-z6y_PbM',
    appId: '1:481748479821:ios:5dc5d5add8af38e8fc5104',
    messagingSenderId: '481748479821',
    projectId: 'restaurants-notifications',
    storageBucket: 'restaurants-notifications.appspot.com',
    iosClientId: '481748479821-fg26doo56lkvb2vg8l5bm86hijlqatt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1qE9XGgNl8YkVyT3bnv-OB97-z6y_PbM',
    appId: '1:481748479821:ios:5dc5d5add8af38e8fc5104',
    messagingSenderId: '481748479821',
    projectId: 'restaurants-notifications',
    storageBucket: 'restaurants-notifications.appspot.com',
    iosClientId: '481748479821-fg26doo56lkvb2vg8l5bm86hijlqatt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantsApp',
  );
}
